import type {
  ToolcraftComponentAcceptance,
  ToolcraftControlSectionInventoryEntry,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";

// The timeline panel was removed: the turntable is decorative, self-running
// motion with no transport for the user to operate. Note that this framework
// forbids pairing an autonomous animation with Export Video (see
// getToolcraftAnimationConfigurationErrors); the product accepts that gate
// failure rather than reinstating a scrubber it does not need.
export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: {
    behaviorCoverage: [
      "no-user-facing-transport",
      "no-play-pause",
      "no-scrub",
      "no-duration-control",
      "no-loop-control",
      "no-export-at-time",
    ],
    mode: "autonomous",
    reason:
      "The turntable is ambient presentation, not an editable animation: it runs one seamless 16-second revolution on the renderer's own clock, with Auto-rotate as the only user control. There is no time to scrub to, no duration to edit, and no frame the user picks — video export always encodes exactly one revolution.",
  },
  mode: "new-toolcraft-app",
};

export const appProductReadiness: ToolcraftProductReadiness = {
  mode: "product",
  productName: "Digital Kintsugi",
  productSummary:
    "An interactive 3D kintsugi visualizer: a procedural porcelain bowl in a studio-lit three.js scene that shatters into Voronoi shards and repairs with raised metallic gold seams.",
  requestedBehavior:
    "Render a real 3D ceramic vessel with orbit camera, studio lighting, and environment reflections; shatter it into irregular mesh shards along Voronoi crack lines with a physics-like settle; repair it with slightly-raised gold ribbons that follow the cracks; expose crack density/branching, seam width, selectable glaze presets, auto-rotate, per-axis rotation, and still image plus turntable video export at a selectable frame rate with easing control.",
};

export const appControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] =
  [
    {
      entity: "Ceramic glaze surface",
      groupingReason:
        "The glaze preset is the full material identity of the vessel surface, finish included.",
      targets: ["vessel.glaze"],
      title: "Glaze",
    },
    {
      entity: "Crack pattern and break state",
      groupingReason:
        "The fracture is authored by striking the bowl itself, so the only control this entity needs is the one that returns that same vessel to its whole, unbroken state.",
      targets: ["vessel.reset"],
      title: "Fracture",
    },
    {
      entity: "Studio lighting rig",
      groupingReason:
        "All five controls scale emitters of the one studio rig that lights the vessel, plus the exposure applied to that same lit image.",
      targets: [
        "lighting.dome",
        "lighting.exposure",
        "lighting.fill",
        "lighting.key",
        "lighting.softbox",
      ],
      title: "Lighting",
    },
    {
      entity: "Turntable motion",
      groupingReason:
        "Auto-rotate enables the self-running revolution and easing shapes the same revolution; both are ambient view settings rather than authored animation, so they sit with Resolution scale in the runtime Setup block.",
      targets: ["turntable.autoRotate", "turntable.easing"],
      title: "Setup",
    },
    {
      entity: "Vessel orientation",
      groupingReason: "Three authored rotation offsets of the same vessel pivot.",
      targets: ["orientation.x", "orientation.y", "orientation.z"],
      title: "Orientation",
    },
    {
      entity: "Scene background",
      groupingReason:
        "Include switch and color edit the same exported scene background.",
      targets: ["export.includeBackground", "scene.background"],
      title: "Background",
    },
    {
      entity: "Still image delivery",
      groupingReason: "Format and resolution configure the same PNG/JPG export.",
      targets: ["export.image.format", "export.image.resolution"],
      title: "Image Export",
    },
    {
      entity: "Turntable video delivery",
      groupingReason:
        "Container, resolution, and frame rate configure the same offline-rendered video export.",
      targets: ["export.video.format", "export.video.fps", "export.video.resolution"],
      title: "Video Export",
    },
  ];

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: glaze preset maps to the glaze material",
    browser: true,
    browserTestName: "browser: kintsugi glaze preset changes the rendered vessel",
    componentType: "imagePicker",
    evidence: "product-output",
    expectedObservable:
      "The rendered vessel pixels change to the selected glaze's color and finish in the 3D preview.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "glaze-preset",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "vessel.glaze",
    userAction: "Click a glaze swatch in the Glaze picker.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: key light scales the key intensity",
    browser: true,
    browserTestName: "browser: kintsugi key light drag rebalances the lit side",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "The side of the vessel facing the key brightens as the value rises and goes flat at 0%.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "lighting-key",
    kind: "control",
    target: "lighting.key",
    userAction: "Drag the Key light slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: fill light scales the fill intensity",
    browser: true,
    browserTestName: "browser: kintsugi fill light drag opens the shadow side",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "The shadow side of the vessel lifts as the value rises and falls to the environment floor at 0%.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "lighting-fill",
    kind: "control",
    target: "lighting.fill",
    userAction: "Drag the Fill light slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: softbox scales the environment key panel",
    browser: true,
    browserTestName: "browser: kintsugi softbox drag changes reflected highlights",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "The reflected highlight across the vessel interior brightens and dims as the value changes, and the gold seams gain and lose their specular glints with it.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "lighting-softbox",
    kind: "control",
    target: "lighting.softbox",
    userAction: "Drag the Softbox slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: ambient dome scales the environment dome",
    browser: true,
    browserTestName: "browser: kintsugi ambient dome drag changes overall fill",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Ambient fill over the whole vessel rises and falls as the value changes, and the gold seams darken and lift with it.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "lighting-ambient-dome",
    kind: "control",
    target: "lighting.dome",
    userAction: "Drag the Ambient dome slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: exposure maps to tone mapping exposure",
    browser: true,
    browserTestName: "browser: kintsugi exposure drag changes image brightness",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "The whole rendered image brightens and darkens during the drag.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "lighting-exposure",
    kind: "control",
    target: "lighting.exposure",
    userAction: "Drag the Exposure slider thumb.",
  },
  {
    actionCoverage: ["reset"],
    automated: true,
    automatedTestName: "kintsugi acceptance: reset returns the vessel to whole",
    browser: true,
    browserTestName: "browser: kintsugi reset action restores the unbroken vessel",
    componentType: "actions",
    evidence: "product-output",
    expectedObservable:
      "After the bowl has been struck and repaired, Reset vessel removes every crack and all the gold, leaving one unbroken bowl.",
    fixture: "Bowl struck once and repaired so gold seams are visible, Auto-rotate off.",
    id: "vessel-reset",
    kind: "control",
    target: "vessel.reset",
    userAction: "Click the bowl, wait for the gold repair, then click Reset vessel.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: auto-rotate gates the turntable yaw",
    browser: true,
    browserTestName: "browser: kintsugi auto-rotate switch resets the turntable pose",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Once the turntable has run past the start of its loop, turning Auto-rotate off snaps the vessel back to its base pose.",
    fixture: "Turntable left running long enough that the yaw is non-zero.",
    id: "turntable-autorotate",
    kind: "control",
    target: "turntable.autoRotate",
    userAction: "Toggle the Auto-rotate switch off.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: easing reshapes revolution timing",
    browser: true,
    browserTestName: "browser: kintsugi easing select changes mid-loop pose and hides with auto-rotate",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "At the same quarter-loop phase the vessel pose differs between Linear and Smooth; the control disappears when Auto-rotate is off.",
    fixture: "Turntable yaw sampled at a quarter of the loop with Auto-rotate on.",
    id: "turntable-easing",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "turntable.easing",
    userAction:
      "Choose Smooth in the Easing select, then toggle Auto-rotate off and on.",
    visibilityCoverage: "all-conditional-visibility",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: orientation x maps to pivot rotation",
    browser: true,
    browserTestName: "browser: kintsugi orientation x drag tilts the vessel live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "The vessel tilts around the X axis during the drag.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "orientation-x",
    kind: "control",
    target: "orientation.x",
    userAction: "Drag the Orientation X slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: orientation y maps to pivot rotation",
    browser: true,
    browserTestName: "browser: kintsugi orientation y drag spins the vessel live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "The vessel spins around the Y axis during the drag.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "orientation-y",
    kind: "control",
    target: "orientation.y",
    userAction: "Drag the Orientation Y slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: orientation z maps to pivot rotation",
    browser: true,
    browserTestName: "browser: kintsugi orientation z drag rolls the vessel live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "The vessel rolls around the Z axis during the drag.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "orientation-z",
    kind: "control",
    target: "orientation.z",
    userAction: "Drag the Orientation Z slider thumb.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: background color reaches the scene clear color",
    browser: true,
    browserTestName: "browser: kintsugi background color changes the studio backdrop",
    componentType: "color",
    evidence: "product-output",
    expectedObservable: "The backdrop behind the vessel renders in the new color.",
    fixture: "Default whole bowl with Auto-rotate off and background included.",
    id: "background-color",
    kind: "control",
    target: "scene.background",
    userAction: "Type a new hex value into the Background color control.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: include background gates preview and exports",
    backgroundOutputCoverage: "all-required-background-output",
    browser: true,
    browserTestName: "browser: kintsugi include background hides the backdrop and exports transparency",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Turning Include off hides the rendered backdrop, PNG export corners become transparent, and video export keeps the backdrop.",
    fixture: "Default whole bowl with Auto-rotate off, exporting at Current resolution.",
    id: "background-include",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle the Background Include switch off, then export PNG and video.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: image format selects the still encoder",
    browser: true,
    browserTestName: "browser: kintsugi image format exports real png and jpg bytes",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "Export PNG produces a decodable PNG for png and a decodable JPEG for jpg.",
    fixture: "Default whole bowl; 2K resolution for fast decode.",
    id: "export-image-format",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "export.image.format",
    userAction: "Export once with PNG selected and once with JPG selected.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: image resolution selects the export long edge",
    browser: true,
    browserTestName: "browser: kintsugi image resolution changes decoded pixel size",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "Decoded exports measure a 2048px long edge for 2K and 4096px for 4K.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "export-image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Export once at 2K and once at 4K, then decode both stills.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: video format chooses a supported container",
    browser: true,
    browserTestName: "browser: kintsugi video format exports mp4 and webm containers",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "Export Video produces a playable MP4 for mp4 and a playable WebM for webm, with capability-checked fallback.",
    fixture: "Current resolution so offline rendering stays fast.",
    id: "export-video-format",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "export.video.format",
    userAction: "Export once with MP4 selected and once with WebM selected.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: video resolution uses encoder-safe sizes",
    browser: true,
    browserTestName: "browser: kintsugi video resolution switches current and 4k output",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "Current exports at the even-rounded canvas size and 4K fits inside 3840x2160 preserving aspect.",
    fixture: "Current resolution so offline rendering stays fast.",
    id: "export-video-resolution",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "export.video.resolution",
    userAction: "Export once at Current and verify the decoded 4K size mapping.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: video fps sets the encoded frame cadence",
    browser: true,
    browserTestName: "browser: kintsugi video fps changes encoded frame count not duration",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "The encoded clip stays one 16-second revolution at every setting while the frame count scales: 384 frames at 24, 480 at 30, and 960 at 60.",
    fixture: "Default whole bowl at Current resolution.",
    id: "export-video-fps",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "export.video.fps",
    userAction: "Export once at 24, once at 30, and once at 60, then decode each clip.",
  },
  {
    actionCoverage: ["export-video", "export-png"],
    automated: true,
    automatedTestName: "kintsugi acceptance: export actions deliver final product output",
    browser: true,
    browserTestName: "browser: kintsugi export actions download real still and video artifacts",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable:
      "Export PNG downloads a decodable still at export resolution and Export Video downloads a video that runs one full 16-second turntable revolution, with the sticky progress accent visible while pending.",
    fixture: "Default whole bowl; video exported at Current resolution and 24 FPS.",
    id: "export-actions",
    kind: "control",
    target: "panel.actions",
    userAction: "Click Export PNG, then click Export Video.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: persistence includes values and panels",
    browser: true,
    browserTestName: "browser: kintsugi settings survive a real page reload",
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "A changed glaze color is still applied to the control and rendered vessel after reloading the page.",
    fixture: "Default app with localStorage persistence enabled.",
    id: "runtime-persistence",
    kind: "runtime",
    persistenceCoverage: "reload",
    target: "vessel.glazeColor",
    userAction: "Change the glaze color, wait for persistence, reload the page.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: striking the bowl breaks it and gold repairs it",
    browser: true,
    browserTestName: "browser: kintsugi clicking the bowl shatters and gold-repairs it",
    componentType: "canvas-strike",
    evidence: "product-output",
    expectedObservable:
      "The vessel loads whole with no gold. Clicking it opens cracks radiating from the point struck, the shards spread and hold, then reassemble with gold flowing along every crack. Clicking again adds a second break to the same network, and the shard count grows until it reaches the 28-shard limit.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "runtime-shatter-cycle",
    kind: "runtime",
    userAction: "Click the bowl in the 3D canvas, wait for the gold repair, then click a different spot.",
  },
  {
    automated: true,
    automatedTestName: "kintsugi acceptance: orbit camera state stays out of exports",
    browser: true,
    browserTestName: "browser: kintsugi pointer drag orbits the camera without moving the viewport",
    componentType: "canvas-orbit",
    evidence: "command-side-effect",
    expectedObservable:
      "Dragging on the product canvas changes the rendered view while runtime canvas zoom and offset stay unchanged.",
    fixture: "Default whole bowl with Auto-rotate off.",
    id: "runtime-orbit",
    kind: "runtime",
    userAction: "Press and drag the pointer across the 3D canvas.",
  },
];
