import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceBudget,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

import { kintsugiRendererPipeline } from "./app-performance-pipeline";

// Budgets are calibrated for a real-time 3D WebGL scene rendered by the
// software rasterizer used in the protected Playwright checkpoint (SwiftShader
// renders one default frame in ~70-110ms at the default 1920x1080 backing).
const dragBudget: ToolcraftPerformanceBudget = {
  maxFrameGapMs: 120,
  maxInteractionMs: 2000,
};
const changeBudget: ToolcraftPerformanceBudget = {
  maxFrameGapMs: 120,
  maxInteractionMs: 2000,
};
const animatedFrameBudget: ToolcraftPerformanceBudget = {
  maxFrameGapMs: 120,
  maxLongTaskMs: 240,
};

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: kintsugiRendererPipeline,
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "webcodecs",
    fidelityRisks: [
      "Fracture boundaries follow the tessellation grid; extremely low grid resolution would make crack staircase steps visible.",
      "The contact shadow is a baked radial disc, so scattered shards do not cast individual moving shadows.",
    ],
    layers: [
      {
        content: ["geometry", "shader"],
        exportMode: "included",
        id: "vessel-3d-scene",
        intentionalRasterizationReason:
          "The product is lit 3D geometry with environment reflections and physically-based gold speculars; it can only exist as a rasterized WebGL scene, not as DOM/SVG vector UI.",
        kind: "product-foreground",
        primitiveCount: "medium",
        renderer: "webgl",
        uiSelector: "[data-toolcraft-product-output] canvas",
      },
    ],
    performanceRisks: [
      "Software WebGL rasterization pays per-pixel for PBR shading; the default backing is 1:1 with output size and Resolution scale above 1 is supersampling headroom for GPU-accelerated machines.",
      "Fracture rebuilds run on the main thread; they are coalesced to one rebuild per frame and measured at 16-25ms at the 28-shard hard limit.",
    ],
    previewExportDifferenceReason:
      "Preview and exports render the same WebGL scene; video export additionally routes the offline-rendered frames through WebCodecs for loop-timed encoding at the selected frame rate.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM/SVG cannot produce lit 3D geometry with environment reflections and physically-based gold speculars.",
      "Canvas 2D would require a CPU software rasterizer for the whole scene on every frame, which is strictly slower than WebGL for this per-pixel shaded workload.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "kintsugi perf: orientation x is a per-frame transform",
      browser: true,
      browserTestName: "browser perf: kintsugi orientation x drag stays live",
      budget: dragBudget,
      controlLabel: "X",
      expectedObservable: "The vessel tilts live during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-orientation-x-drag",
      interaction: "control-drag",
      target: "orientation.x",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: orientation y is a per-frame transform",
      browser: true,
      browserTestName: "browser perf: kintsugi orientation y drag stays live",
      budget: dragBudget,
      controlLabel: "Y",
      expectedObservable: "The vessel spins live during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-orientation-y-drag",
      interaction: "control-drag",
      target: "orientation.y",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: orientation z is a per-frame transform",
      browser: true,
      browserTestName: "browser perf: kintsugi orientation z drag stays live",
      budget: dragBudget,
      controlLabel: "Z",
      expectedObservable: "The vessel rolls live during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-orientation-z-drag",
      interaction: "control-drag",
      target: "orientation.z",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: glaze preset is a material uniform update",
      browser: true,
      browserTestName: "browser perf: kintsugi glaze preset change re-renders once",
      budget: changeBudget,
      controlLabel: "Glaze",
      expectedObservable: "Vessel glaze changes in the rendered output.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-glaze-preset-change",
      interaction: "control-change",
      target: "vessel.glaze",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: key light is a light intensity write",
      browser: true,
      browserTestName: "browser perf: kintsugi key light drag stays live",
      budget: dragBudget,
      controlLabel: "Key light",
      expectedObservable: "The lit side of the vessel brightens and darkens during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-key-light-drag",
      interaction: "control-drag",
      target: "lighting.key",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: fill light is a light intensity write",
      browser: true,
      browserTestName: "browser perf: kintsugi fill light drag stays live",
      budget: dragBudget,
      controlLabel: "Fill light",
      expectedObservable: "The shadow side of the vessel opens up and closes during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-fill-light-drag",
      interaction: "control-drag",
      target: "lighting.fill",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: exposure is a tone mapping scalar",
      browser: true,
      browserTestName: "browser perf: kintsugi exposure drag stays live",
      budget: dragBudget,
      controlLabel: "Exposure",
      expectedObservable: "Overall image brightness tracks the thumb during the drag.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-exposure-drag",
      interaction: "control-drag",
      target: "lighting.exposure",
      workload: false,
    },
    // Softbox and Ambient dome are emitters inside the prefiltered environment
    // maps, so each committed value re-bakes them. There are two: the studio
    // cove for the glaze and bisque, and the gold seams' own light box. That is
    // real per-change work rather than a scalar write, hence workload rather
    // than responsiveness, and the renderer coalesces a drag to one bake of the
    // pair per frame.
    {
      automated: true,
      automatedTestName: "kintsugi perf: softbox rebake stays within the frame budget",
      browser: true,
      browserTestName: "browser perf: kintsugi softbox drag at full panel output",
      budget: dragBudget,
      controlLabel: "Softbox",
      expectedObservable:
        "Reflected highlights on the vessel and the gold seams brighten and dim live during the drag.",
      fixture: "Whole bowl, Auto-rotate off, drag Softbox to 200%.",
      id: "perf-softbox-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 200,
          metric: "numeric-max",
          smoothTarget: 200,
          smoothTargetRatio: 1,
          target: "lighting.softbox",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "200% is the schema maximum; the environment bake cost is the same at any value, so the maximum is the worst case for both bake and shading.",
        value: 200,
      },
      target: "lighting.softbox",
      workload: true,
      workloadFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 200,
          metric: "numeric-max",
          smoothTarget: 200,
          smoothTargetRatio: 1,
          target: "lighting.softbox",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Full panel output is the guaranteed-smooth heavy baseline the drag must reach.",
        value: 200,
      },
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: ambient dome rebake stays within the frame budget",
      browser: true,
      browserTestName: "browser perf: kintsugi ambient dome drag at full output",
      budget: dragBudget,
      controlLabel: "Ambient dome",
      expectedObservable:
        "Overall fill on the vessel and the gold seams brightens and dims live during the drag.",
      fixture: "Whole bowl, Auto-rotate off, drag Ambient dome to 100%.",
      id: "perf-ambient-dome-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "lighting.dome",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "100% is the schema maximum; the environment bake cost is value-independent, so the maximum is the worst case for both bake and shading.",
        value: 100,
      },
      target: "lighting.dome",
      workload: true,
      workloadFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "lighting.dome",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Full dome output is the guaranteed-smooth heavy baseline the drag must reach.",
        value: 100,
      },
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: auto-rotate toggles yaw only",
      browser: true,
      browserTestName: "browser perf: kintsugi auto-rotate toggle re-renders once",
      budget: changeBudget,
      controlLabel: "Auto-rotate",
      expectedObservable: "The vessel pose snaps to the base orientation.",
      fixture: "Turntable left running so yaw is non-zero.",
      id: "perf-autorotate-change",
      interaction: "control-change",
      target: "turntable.autoRotate",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: easing changes a per-frame formula",
      browser: true,
      browserTestName: "browser perf: kintsugi easing change re-renders once",
      budget: changeBudget,
      controlLabel: "Easing",
      expectedObservable: "The mid-loop vessel pose changes between Linear and Smooth.",
      fixture: "Turntable yaw sampled at a quarter of the loop with Auto-rotate on.",
      id: "perf-easing-change",
      interaction: "control-change",
      target: "turntable.easing",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: background color sets the clear color",
      browser: true,
      browserTestName: "browser perf: kintsugi background color change re-renders once",
      budget: changeBudget,
      expectedObservable: "The backdrop color changes in the rendered output.",
      fixture: "Whole bowl, Auto-rotate off, background included.",
      id: "perf-background-color-change",
      interaction: "control-change",
      target: "scene.background",
      uiSelector: '[data-toolcraft-control-target="scene.background"]',
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: include background toggles transparency",
      browser: true,
      browserTestName: "browser perf: kintsugi include background toggle re-renders once",
      budget: changeBudget,
      controlLabel: "Include",
      expectedObservable: "The rendered backdrop disappears or reappears.",
      fixture: "Whole bowl, Auto-rotate off.",
      id: "perf-include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: image format only reconfigures the still encoder",
      browser: true,
      browserTestName: "browser perf: kintsugi image format select responds instantly",
      budget: changeBudget,
      controlLabel: "Format",
      expectedObservable: "The Image Export format select shows the chosen option.",
      fixture: "Default app state.",
      id: "perf-image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: image resolution bounds still export cost",
      browser: true,
      browserTestName: "browser perf: kintsugi image resolution select reaches 8k",
      budget: changeBudget,
      controlLabel: "Resolution",
      expectedObservable: "The Image Export resolution select shows the 8K hard limit.",
      fixture: "Default app state; 8K is the still export hard limit.",
      id: "perf-image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest still export long edge the schema offers.",
        value: "8k",
      },
      target: "export.image.resolution",
      workload: true,
      workloadFixture: {
        // 28 shard meshes: the vessel's heaviest reachable geometry, and the
        // baseline every export-setting change is measured against.
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "custom",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Export settings are changed against the heaviest scene the vessel can reach: the 28-shard cap.",
        value: 28,
      },
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: video format only reconfigures the container",
      browser: true,
      browserTestName: "browser perf: kintsugi video format select responds instantly",
      budget: changeBudget,
      controlLabel: "Format",
      expectedObservable: "The Video Export format select shows the chosen option.",
      fixture: "Default app state.",
      id: "perf-video-format-change",
      interaction: "control-change",
      target: "export.video.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: video resolution bounds video export cost",
      browser: true,
      browserTestName: "browser perf: kintsugi video resolution select reaches 4k",
      budget: changeBudget,
      controlLabel: "Resolution",
      expectedObservable: "The Video Export resolution select shows the 4K hard limit.",
      fixture: "Default app state; 4K is the video export hard limit.",
      id: "perf-video-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "4k",
          metric: "custom",
          smoothTarget: "4k",
          smoothTargetRatio: 1,
          target: "export.video.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the largest video export size the schema offers.",
        value: "4k",
      },
      target: "export.video.resolution",
      workload: true,
      workloadFixture: {
        // 28 shard meshes: the vessel's heaviest reachable geometry, and the
        // baseline every export-setting change is measured against.
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "custom",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "export.video.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Export settings are changed against the heaviest scene the vessel can reach: the 28-shard cap.",
        value: 28,
      },
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: video fps bounds the encoded frame count",
      browser: true,
      browserTestName: "browser perf: kintsugi video fps select reaches 60",
      budget: changeBudget,
      controlLabel: "FPS",
      expectedObservable: "The Video Export FPS select shows the 60 hard limit.",
      fixture: "Default app state; 60 is the highest frame rate the schema offers.",
      id: "perf-video-fps-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "60",
          metric: "custom",
          smoothTarget: "60",
          smoothTargetRatio: 1,
          target: "export.video.fps",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "60 FPS is the largest frame count the schema offers: 720 frames for the 12-second loop, twice the default.",
        value: "60",
      },
      target: "export.video.fps",
      workload: true,
      workloadFixture: {
        // Same 28-shard baseline the other export settings are measured
        // against, so frame-rate cost is comparable to resolution cost.
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "custom",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "export.video.fps",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Export settings are changed against the heaviest scene the vessel can reach: the 28-shard cap.",
        value: 28,
      },
    },
    {
      actionValue: "export-png",
      automated: true,
      automatedTestName: "kintsugi perf: still export renders offline at export size",
      browser: true,
      browserTestName: "browser perf: kintsugi export png completes a real download",
      budget: { maxExportMs: 8000 },
      completionEvidence: "download",
      controlLabel: "Export PNG",
      expectedObservable: "A PNG download completes at the selected export resolution.",
      fixture: "Default 4K still export of the whole bowl.",
      id: "perf-export-png",
      interaction: "export-copy",
      workload: false,
    },
    {
      actionValue: "export-video",
      automated: true,
      automatedTestName: "kintsugi perf: video export encodes loop-timed frames",
      browser: true,
      browserTestName: "browser perf: kintsugi export video completes a real download",
      budget: { maxExportMs: 8000 },
      completionEvidence: "download",
      controlLabel: "Export Video",
      expectedObservable: "A video download completes with offline-rendered frames.",
      fixture: "Video exported at Current resolution and 24 FPS so the offline render stays bounded.",
      id: "perf-export-video",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: reset rebuilds the whole vessel within budget",
      browser: true,
      browserTestName: "browser perf: kintsugi reset action responds within budget",
      budget: changeBudget,
      controlLabel: "Reset vessel",
      expectedObservable:
        "The cracks and gold disappear and one unbroken bowl renders right after the click.",
      fixture:
        "Struck and repaired bowl, Auto-rotate off; Reset discards the break history and rebuilds the fracture.",
      id: "perf-vessel-reset-change",
      interaction: "control-change",
      target: "vessel.reset",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: first preview renders within budget",
      browser: true,
      browserTestName: "browser perf: kintsugi preview re-renders after a pattern change",
      budget: { maxFrameGapMs: 120, maxPreviewMs: 2000 },
      expectedObservable: "A full fracture rebuild reaches the rendered canvas within the preview budget.",
      fixture:
        "Default whole bowl; the bowl is struck so a full fracture and seam rebuild has to reach the canvas.",
      id: "perf-preview-render",
      interaction: "preview-render",
      uiSelector: "[data-toolcraft-product-output] canvas",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: worst-case fracture stays within frame budgets",
      browser: true,
      browserTestName: "browser perf: kintsugi playback frames at maximum fracture stress",
      budget: animatedFrameBudget,
      expectedObservable: "Turntable playback keeps animating at the combined fracture hard limit.",
      fixture: "Bowl struck until it reaches the 28-shard cap, turntable running.",
      id: "perf-animation-frame-stress",
      interaction: "animation-frame",
      stress: true,
      stressFixture: {
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "count",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "vessel.shardCount",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The 28-shard accumulation cap is the heaviest geometry the vessel can reach, however many times it is struck.",
        value: 28,
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: the turntable loop drives one render per frame",
      browser: true,
      browserTestName: "browser perf: kintsugi turntable frame cadence",
      budget: animatedFrameBudget,
      expectedObservable: "The turntable advances on its own clock without frame stalls.",
      fixture: "Default whole bowl with Auto-rotate on.",
      id: "perf-turntable-loop",
      interaction: "animation-frame",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: viewport drag suspends animation work",
      browser: true,
      browserTestName: "browser perf: kintsugi canvas drag while the turntable plays",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 240 },
      expectedObservable:
        "Dragging over the canvas keeps frames responsive while playback state is preserved.",
      fixture: "Default whole bowl with the turntable running.",
      id: "perf-animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "count",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "vessel.shardCount",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Dragging over the animated canvas must stay smooth at the 28-shard accumulation cap.",
        value: 28,
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: toolbar zoom stays smooth at maximum stress",
      browser: true,
      browserTestName: "browser perf: kintsugi toolbar zoom at maximum fracture stress",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 240 },
      expectedObservable: "Toolbar zoom in/out stays responsive at the fracture hard limit.",
      fixture: "Bowl struck until it reaches the 28-shard cap before zooming.",
      id: "perf-viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "many-items",
        loadProfile: {
          hardLimit: 28,
          metric: "count",
          smoothTarget: 28,
          smoothTargetRatio: 1,
          target: "vessel.shardCount",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Zoom must stay responsive at the 28-shard accumulation cap.",
        value: 28,
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "kintsugi perf: control edits never move the canvas viewport",
      browser: true,
      browserTestName: "browser perf: kintsugi viewport stays stable during control edits",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Canvas zoom and offset stay fixed while product controls change.",
      fixture: "Default whole bowl, Auto-rotate off.",
      id: "perf-viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "export.image.resolution",
    "export.video.fps",
    "export.video.resolution",
    "lighting.dome",
    "lighting.softbox",
  ],
});
